### ISSUE TITLE
Regression in Event payment in backend  - 4.6

### ISSUE THREAD

**Issue by aydun** [drastik/com.drastikbydesign.stripe#220] opened 2017-06-19 13:39 UTC
On 4.6, going to contact > events tab > Submit Credit Card Registration > select a paid event,  the billing fields should load but this commit causes a regression and the fields no longer load:
https://github.com/drastik/com.drastikbydesign.stripe/commit/38621a92424f76ca99471b4885e1bcaf028b1b27

**Comment by h-c-c** [comment] 2017-06-19 15:19
Duplicate of #218

**Closed as completed by h-c-c** 2017-06-19 15:19 UTC

**Comment by aydun** [comment] 2017-06-19 17:26
The title of #218 is relevant but the symptoms reported there are different. 218 is about membership, this is about events.  218 has errors about protected properties, this does not. 218 describes a white screen, this is similar but different - the billing fields are not loaded after the event is selected.

It may have the same underlying cause but the symptoms are different.  FWIW the regression is specifically linked to the referenced commit.  Before that commit, the fields are displayed.  With it, they don't.
