### ISSUE TITLE
Persistent error: Stripe.js token was not passed! on Joomla

### ISSUE THREAD

**Issue by iywuk** [drastik/com.drastikbydesign.stripe#98] opened 2015-09-14 11:16 UTC
m getting the following error on civicrm

Persistent error: Stripe.js token was not passed!

im using joomla version 3.4.4
and CiviCRM Version 4.6.8

Can you help please as I have gone through the issues on gitshub and cannot find out how to correct this.

**Comment by jmcclelland** [comment] 2015-09-16 16:01
This looks like a duplicate of https://github.com/drastik/com.drastikbydesign.stripe/issues/76

**Comment by drastik** [comment] 2015-10-09 19:04
Should be fixed as of today.
https://github.com/drastik/com.drastikbydesign.stripe/commit/4ee7e494ca2bf6494f281c6c6fd0bb29c2fe766e

**Closed as completed by drastik** 2015-10-09 19:04 UTC
